### PR TITLE
feat: use pnpm

### PR DESCRIPTION
**Pull request by izayl**

### CODE REVIEW

**Comment by glitch-txs** [comment]
Cool, thanks!
Seems like vercel deployment is failing, do I need to change config from Vercel Dashboard?

**Comment by izayl** [comment]
no need, let me update the scripts, should build packages before vercel web build

**Comment by izayl** [comment]
@glitch-txs 
vercel config need update:

*w3vm-docs*

- [ ] build command: `pnpm run build:docs`


*w3vm-web3modal*

- [ ] build command: `pnpm run build:web3modal`

**Comment by izayl** [comment]
@glitch-txs any problems?

**Comment by glitch-txs** [comment]
Hi I'll take a look once I have some free time, been busy lately 😅

**Pull request merged**
