### PR TITLE
Add pnpm and turbo

### PR DESCRIPTION
**Pull request by glitch-txs**

### CODE REVIEW

**Comment by glitch-txs** [comment]
@izayl I'm getting this when running `pnpm run build:packages`

`@w3vm/web3modal-ethers-5:build: X [ERROR] Could not resolve "vanilla-cafe"`

Do you know what could it be?

Same for `@w3vm/walletconnect:build:`

The dependency is a sub dep of `@w3vm/core`

This seems to be the issue with the deployment, the rest of script weren't required it seems :)

**Comment by glitch-txs** [comment]
Also can we select the order of the builds? seems like they depend on the dist folder so if the core is not built first the rest will fail on the first run

**Comment by glitch-txs** [comment]
resloved by adding missing peer dependencies explicitly. (I didn't have to change Vercel config btw)

Now, seems like clean and dev scripts don't work

**Comment by glitch-txs** [comment]
Seems like turbo/pnpm was getting .next build forder as a workspace. Solved with this filter https://github.com/vercel/turbo/issues/3340#issuecomment-1508235744

**Review by izayl — APPROVED** [review]

**Pull request merged**
